# Generated by Django 5.2.9 on 2026-05-31 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('department', models.CharField(blank=True, help_text='Department or team name', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, help_text='Job designation', max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='User biography', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Current user status', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_login_tracked', models.DateTimeField(blank=True, help_text='Last login time (custom tracking)', null=True)),
                ('role', models.ForeignKey(blank=True, help_text='Assigned role for RBAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.role')),
                ('user', models.OneToOneField(help_text='Reference to Django User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['user__first_name'],
            },
        ),
    ]
