# Generated by Django 5.2.9 on 2026-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Cache key identifier', max_length=255, unique=True)),
                ('value', models.JSONField(help_text='Cached data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Cache expiration time', null=True)),
            ],
            options={
                'verbose_name': 'Dashboard Cache',
                'verbose_name_plural': 'Dashboard Cache',
                'db_table': 'dashboard_cache',
            },
        ),
    ]
