# Generated by Django 5.2.9 on 2026-05-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('guest', 'Guest')], help_text='Role name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the role and its responsibilities', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view_user', 'View User'), ('add_user', 'Add User'), ('change_user', 'Change User'), ('delete_user', 'Delete User'), ('view_role', 'View Role'), ('add_role', 'Add Role'), ('change_role', 'Change Role'), ('delete_role', 'Delete Role'), ('view_task', 'View Task'), ('add_task', 'Add Task'), ('change_task', 'Change Task'), ('delete_task', 'Delete Task'), ('assign_task', 'Assign Task'), ('view_dashboard', 'View Dashboard'), ('view_reports', 'View Reports'), ('admin_access', 'Admin Access')], help_text='Permission code', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this permission allows', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='Role this permission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.role')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
